# Use new container infrastructure to enable caching
sudo: false
# language: haskell

# do not send Travis CI email notifications
notifications:
 email: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  # - $HOME/.cabal
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

matrix:
  include:
  - env: ARGS="--resolver nightly"
    compiler: ": #GHC HEAD"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS=""
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-9"
    compiler: ": #stack 8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-11"
    compiler: ": #stack 8.2.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-12"
    compiler: ": #stack 8.4.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-13"
    compiler: ": #stack 8.6.5"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--resolver lts-14"
    compiler: ": #stack 8.6.5"
    addons: {apt: {packages: [libgmp-dev]}}

script:
  - stack --no-terminal --skip-ghc-check test