resolver: lts-14.16
packages:
- '.'
extra-deps:
- hgal-2.0.0.2
- algebraic-graphs-0.4
- unordered-containers-0.2.10.0
- selective-0.3
- html-entities-1.1.4.3
- mmorph-1.1.3
- exceptions-0.10.4
- semigroups-0.18.3
- xeno-0.3.5.2