resolver: lts-12.1
compiler-check: newer-minor
packages:
- '.'
# - /home/rob/code/haskell/xmlbf/xmlbf
# - /home/rob/code/haskell/xmlbf/xmlbf-xeno
extra-deps:
- hgal-2.0.0.2
- git: git@gitlab.com:k0001/xmlbf.git
  commit: f46b96a401ac2ef6f30f8939c9f7bf92f38df383
  subdirs:
  - xmlbf
  - xmlbf-xeno