resolver: lts-12.1
compiler-check: newer-minor
packages:
- '.'
extra-deps:
- hgal-2.0.0.2
- algebraic-graphs-0.4
- unordered-containers-0.2.10.0
# - xmlbf-0.6
- selective-0.2
- git: https://gitlab.com/k0001/xmlbf.git
  commit: 8d6b4e9c8d4e5c768e0c0d9db8de114b946e9aaf
  subdirs:
  - xmlbf
  - xmlbf-xeno
